using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_JobData : MonoBehaviour
{
    public GameEvent_JobData Event;
    public UnityEvent_JobData Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(JobData jobData)
    {
        Response.Invoke(jobData);
    }
}

[System.Serializable]
public class UnityEvent_JobData : UnityEvent<JobData>
{
}
