using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_RiftSettings : MonoBehaviour
{
    public GameEvent_RiftSettings Event;
    public UnityEvent_RiftSettings Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(RiftSettings integer)
    {
        Response.Invoke(integer);
    }
}

[System.Serializable]
public class UnityEvent_RiftSettings : UnityEvent<RiftSettings>
{
}
