using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TooltipDisabler : MonoBehaviour
{
    [SerializeField] private GameObject itemTooltip;
    [SerializeField] private GameObject statTooltip;

    [SerializeField] private UIKeyBinder keyBinder;

    private void Awake()
    {
        keyBinder.OnUIVisibilityChanged.AddListener((isVisible) =>
        {
            if (isVisible) return;

            itemTooltip.SetActive(isVisible);
            statTooltip.SetActive(isVisible);
        });
    }
}
