using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameScene : MonoBehaviour
{
    [SerializeField] private ZoneData zone;
    [SerializeField] private GameEvent_ZoneData onGameSceneLoaded;
    [SerializeField] private List<Transform> spawnPoints = new List<Transform>();

    private void Awake()
    {
        zone.spawnPoints = spawnPoints;
        onGameSceneLoaded.Raise(zone);
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }
}
