using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_AbilityKeyBinder : MonoBehaviour
{
    public GameEvent_AbilityKeyBinder Event;
    public UnityEvent_AbilityKeyBinder Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(AbilityKeyBinder jobData)
    {
        Response.Invoke(jobData);
    }
}

[System.Serializable]
public class UnityEvent_AbilityKeyBinder : UnityEvent<AbilityKeyBinder>
{
}
