using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_Int : MonoBehaviour
{
    public GameEvent_Int Event;
    public UnityEvent_Int Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(int integer)
    {
        Response.Invoke(integer);
    }
}

[System.Serializable]
public class UnityEvent_Int : UnityEvent<int>
{
}
