using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class SetNickName : MonoBehaviour
{
    [SerializeField] protected StringSharedField insertedName;
    [SerializeField] protected Button button;

    protected virtual void Start()
    {
        button.interactable = false;
    }
    public virtual void OnInputFieldChanged(string value)
    {
        insertedName.Value = value;
        //PhotonNetwork.NickName = value;
        button.interactable = !string.IsNullOrEmpty(value);
    }
}
