using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_ZoneData : MonoBehaviour
{
    public GameEvent_ZoneData Event;
    public UnityEvent_ZoneData Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(ZoneData jobData)
    {
        Response.Invoke(jobData);
    }
}

[System.Serializable]
public class UnityEvent_ZoneData : UnityEvent<ZoneData>
{
}
