using Photon.Pun;
using Photon.Realtime;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_Player : MonoBehaviour
{
    public GameEvent_Player Event;
    public UnityEvent_Player Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(Player photonView)
    {
        Response.Invoke(photonView);
    }
}

[System.Serializable]
public class UnityEvent_Player : UnityEvent<Player>
{
}
