using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener_Int_Int : MonoBehaviour
{
    public GameEvent_Int_Int Event;
    public UnityEvent_Int_Int Response;

    private void OnEnable()
    {
        Event.RegisterListener(this);
    }

    private void OnDisable()
    {
        Event.UnRegisterListener(this);
    }

    public void OnEventRaised(int integer, int integer2)
    {
        Response.Invoke(integer, integer2);
    }
}

[System.Serializable]
public class UnityEvent_Int_Int : UnityEvent<int,int>
{
}
