using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class SetNickName : MonoBehaviour
{
    [SerializeField] private StringSharedField accountName;
    [SerializeField] private Button button;

    private void Start()
    {
        button.interactable = false;
    }
    public void OnInputFieldChanged(string value)
    {
        accountName.Value = value;
        //PhotonNetwork.NickName = value;
        button.interactable = !string.IsNullOrEmpty(value);
    }
}
